### ISSUE TITLE
Review of weapons, equipment and related mods

### ISSUE THREAD

**Issue by adampiskorski** [zulu-alpha/Issue-Tracking#40]

**Comment by ZA-Wolf** [comment]
Weapons, Assets and Equipment

Intent: Develop standard for grading performance (precision, accuracy, weight etc) , functionality, overall value, adherence to real-life equivalent and aesthetics.

**Comment by ZA-Wolf** [comment]
WIP Grading template.  

Zulu Alpha - Weapon System Grading Template 2019 - 

https://drive.google.com/open?id=1zBNH3mUs4Lsg1VnjIkmKI6GOPJ5Y4S9hrO75IDv09Oo

**Comment by ZA-Wolf** [comment]
ZA Modline Review and Roadmap Proposal 2019

https://drive.google.com/open?id=1I6S-Le-COAPPgFHxkFcGxOyDsdgwLBtF
