### ISSUE TITLE
Propsective Guide

### ISSUE THREAD

**Issue by Bakgat22** [zulu-alpha/Issue-Tracking#50]
https://docs.google.com/document/d/1jITQcjxLl4gVQDDV_DTHsXeYTqrmP617aZFQFhVpGjw/edit?usp=sharing

Initial: Document needs attention, Some are outdated

**Comment by adampiskorski** [comment]
What sections need to be looked at?

**Comment by Bakgat22** [comment]
Discord Links.
Artwork Old.
Photos - Old Fatigues.

To be franked the Document looks like it was made on Word 2007. We could Give it banners. Borders etc. 

Make it visually Appealing.

**Comment by Bakgat22** [comment]
https://discordapp.com/invite/beKxUV4

**Comment by Bakgat22** [comment]
[Prospective Guide V3-0-0.docx](https://github.com/zulu-alpha/Issue-Tracking/files/4707879/Prospective.Guide.V3-0-0.docx)
 This is just an Idea, it's not complete nor correctly Grammar and Paraphrasing. Important to Start Versioning this document too. 

Initial: V3-0-0.

**Comment by Bakgat22** [comment]
[Prospective Guide V3-0-1.pdf](https://github.com/zulu-alpha/Issue-Tracking/files/4709334/Prospective.Guide.V3-0-1.pdf)

**Comment by Bakgat22** [comment]
[Prospective Guide V3-0-3.pdf](https://github.com/zulu-alpha/Issue-Tracking/files/4713724/Prospective.Guide.V3-0-3.pdf)
[prospectiveGuide2020_V##.pptx](https://github.com/zulu-alpha/Issue-Tracking/files/4713725/prospectiveGuide2020_V.pptx)

Feat: Final Amemded
Ready for publication: V3-0-3

**Comment by Bakgat22** [comment]
Thanks to all the input from All parties involved. Prospective Guide is now up to date.
